/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.phenix.orderrouter.ctp;

public class CThostFtdcSuperUserFunctionField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcSuperUserFunctionField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcSuperUserFunctionField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTP_wrap4javaJNI.delete_CThostFtdcSuperUserFunctionField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUserID(String value) {
    CTP_wrap4javaJNI.CThostFtdcSuperUserFunctionField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return CTP_wrap4javaJNI.CThostFtdcSuperUserFunctionField_UserID_get(swigCPtr, this);
  }

  public void setFunctionCode(char value) {
    CTP_wrap4javaJNI.CThostFtdcSuperUserFunctionField_FunctionCode_set(swigCPtr, this, value);
  }

  public char getFunctionCode() {
    return CTP_wrap4javaJNI.CThostFtdcSuperUserFunctionField_FunctionCode_get(swigCPtr, this);
  }

  public CThostFtdcSuperUserFunctionField() {
    this(CTP_wrap4javaJNI.new_CThostFtdcSuperUserFunctionField(), true);
  }

  public void CopyTo(CThostFtdcSuperUserFunctionField r) {
    CTP_wrap4javaJNI.CThostFtdcSuperUserFunctionField_CopyTo(swigCPtr, this, CThostFtdcSuperUserFunctionField.getCPtr(r), r);
  }

}
