/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.phenix.orderrouter.ctp;

public class CThostFtdcBrokerUserField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcBrokerUserField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcBrokerUserField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTP_wrap4javaJNI.delete_CThostFtdcBrokerUserField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    CTP_wrap4javaJNI.CThostFtdcBrokerUserField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return CTP_wrap4javaJNI.CThostFtdcBrokerUserField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    CTP_wrap4javaJNI.CThostFtdcBrokerUserField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return CTP_wrap4javaJNI.CThostFtdcBrokerUserField_UserID_get(swigCPtr, this);
  }

  public void setUserName(String value) {
    CTP_wrap4javaJNI.CThostFtdcBrokerUserField_UserName_set(swigCPtr, this, value);
  }

  public String getUserName() {
    return CTP_wrap4javaJNI.CThostFtdcBrokerUserField_UserName_get(swigCPtr, this);
  }

  public void setUserType(char value) {
    CTP_wrap4javaJNI.CThostFtdcBrokerUserField_UserType_set(swigCPtr, this, value);
  }

  public char getUserType() {
    return CTP_wrap4javaJNI.CThostFtdcBrokerUserField_UserType_get(swigCPtr, this);
  }

  public void setIsActive(int value) {
    CTP_wrap4javaJNI.CThostFtdcBrokerUserField_IsActive_set(swigCPtr, this, value);
  }

  public int getIsActive() {
    return CTP_wrap4javaJNI.CThostFtdcBrokerUserField_IsActive_get(swigCPtr, this);
  }

  public void setIsUsingOTP(int value) {
    CTP_wrap4javaJNI.CThostFtdcBrokerUserField_IsUsingOTP_set(swigCPtr, this, value);
  }

  public int getIsUsingOTP() {
    return CTP_wrap4javaJNI.CThostFtdcBrokerUserField_IsUsingOTP_get(swigCPtr, this);
  }

  public CThostFtdcBrokerUserField() {
    this(CTP_wrap4javaJNI.new_CThostFtdcBrokerUserField(), true);
  }

  public void CopyTo(CThostFtdcBrokerUserField r) {
    CTP_wrap4javaJNI.CThostFtdcBrokerUserField_CopyTo(swigCPtr, this, CThostFtdcBrokerUserField.getCPtr(r), r);
  }

}
