/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.phenix.orderrouter.ctp;

public class CThostFtdcReqAuthenticateField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcReqAuthenticateField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcReqAuthenticateField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTP_wrap4javaJNI.delete_CThostFtdcReqAuthenticateField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    CTP_wrap4javaJNI.CThostFtdcReqAuthenticateField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return CTP_wrap4javaJNI.CThostFtdcReqAuthenticateField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    CTP_wrap4javaJNI.CThostFtdcReqAuthenticateField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return CTP_wrap4javaJNI.CThostFtdcReqAuthenticateField_UserID_get(swigCPtr, this);
  }

  public void setUserProductInfo(String value) {
    CTP_wrap4javaJNI.CThostFtdcReqAuthenticateField_UserProductInfo_set(swigCPtr, this, value);
  }

  public String getUserProductInfo() {
    return CTP_wrap4javaJNI.CThostFtdcReqAuthenticateField_UserProductInfo_get(swigCPtr, this);
  }

  public void setAuthCode(String value) {
    CTP_wrap4javaJNI.CThostFtdcReqAuthenticateField_AuthCode_set(swigCPtr, this, value);
  }

  public String getAuthCode() {
    return CTP_wrap4javaJNI.CThostFtdcReqAuthenticateField_AuthCode_get(swigCPtr, this);
  }

  public CThostFtdcReqAuthenticateField() {
    this(CTP_wrap4javaJNI.new_CThostFtdcReqAuthenticateField(), true);
  }

  public void CopyTo(CThostFtdcReqAuthenticateField r) {
    CTP_wrap4javaJNI.CThostFtdcReqAuthenticateField_CopyTo(swigCPtr, this, CThostFtdcReqAuthenticateField.getCPtr(r), r);
  }

}
