/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.phenix.orderrouter.ctp;

public class CThostFtdcAccountregisterField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcAccountregisterField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcAccountregisterField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTP_wrap4javaJNI.delete_CThostFtdcAccountregisterField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradeDay(String value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_TradeDay_set(swigCPtr, this, value);
  }

  public String getTradeDay() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_TradeDay_get(swigCPtr, this);
  }

  public void setBankID(String value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_BankID_set(swigCPtr, this, value);
  }

  public String getBankID() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_BankID_get(swigCPtr, this);
  }

  public void setBankBranchID(String value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_BankBranchID_set(swigCPtr, this, value);
  }

  public String getBankBranchID() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_BankBranchID_get(swigCPtr, this);
  }

  public void setBankAccount(String value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_BankAccount_set(swigCPtr, this, value);
  }

  public String getBankAccount() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_BankAccount_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_BrokerID_get(swigCPtr, this);
  }

  public void setBrokerBranchID(String value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_BrokerBranchID_set(swigCPtr, this, value);
  }

  public String getBrokerBranchID() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_BrokerBranchID_get(swigCPtr, this);
  }

  public void setAccountID(String value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_AccountID_set(swigCPtr, this, value);
  }

  public String getAccountID() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_AccountID_get(swigCPtr, this);
  }

  public void setIdCardType(char value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_IdCardType_set(swigCPtr, this, value);
  }

  public char getIdCardType() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_IdCardType_get(swigCPtr, this);
  }

  public void setIdentifiedCardNo(String value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_IdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getIdentifiedCardNo() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_IdentifiedCardNo_get(swigCPtr, this);
  }

  public void setCustomerName(String value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_CustomerName_set(swigCPtr, this, value);
  }

  public String getCustomerName() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_CustomerName_get(swigCPtr, this);
  }

  public void setCurrencyID(String value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_CurrencyID_set(swigCPtr, this, value);
  }

  public String getCurrencyID() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_CurrencyID_get(swigCPtr, this);
  }

  public void setOpenOrDestroy(char value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_OpenOrDestroy_set(swigCPtr, this, value);
  }

  public char getOpenOrDestroy() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_OpenOrDestroy_get(swigCPtr, this);
  }

  public void setRegDate(String value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_RegDate_set(swigCPtr, this, value);
  }

  public String getRegDate() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_RegDate_get(swigCPtr, this);
  }

  public void setOutDate(String value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_OutDate_set(swigCPtr, this, value);
  }

  public String getOutDate() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_OutDate_get(swigCPtr, this);
  }

  public void setTID(int value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_TID_set(swigCPtr, this, value);
  }

  public int getTID() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_TID_get(swigCPtr, this);
  }

  public void setCustType(char value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_CustType_set(swigCPtr, this, value);
  }

  public char getCustType() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_CustType_get(swigCPtr, this);
  }

  public void setBankAccType(char value) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_BankAccType_set(swigCPtr, this, value);
  }

  public char getBankAccType() {
    return CTP_wrap4javaJNI.CThostFtdcAccountregisterField_BankAccType_get(swigCPtr, this);
  }

  public CThostFtdcAccountregisterField() {
    this(CTP_wrap4javaJNI.new_CThostFtdcAccountregisterField(), true);
  }

  public void CopyTo(CThostFtdcAccountregisterField r) {
    CTP_wrap4javaJNI.CThostFtdcAccountregisterField_CopyTo(swigCPtr, this, CThostFtdcAccountregisterField.getCPtr(r), r);
  }

}
