/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.phenix.orderrouter.ctp;

public class CThostFtdcTraderSpi {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcTraderSpi(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcTraderSpi obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTP_wrap4javaJNI.delete_CThostFtdcTraderSpi(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    CTP_wrap4javaJNI.CThostFtdcTraderSpi_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    CTP_wrap4javaJNI.CThostFtdcTraderSpi_change_ownership(this, swigCPtr, true);
  }

  public void OnFrontConnected() {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnFrontConnected(swigCPtr, this); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnFrontConnectedSwigExplicitCThostFtdcTraderSpi(swigCPtr, this);
  }

  public void OnFrontDisconnected(int nReason) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnFrontDisconnected(swigCPtr, this, nReason); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnFrontDisconnectedSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, nReason);
  }

  public void OnHeartBeatWarning(int nTimeLapse) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnHeartBeatWarning(swigCPtr, this, nTimeLapse); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnHeartBeatWarningSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, nTimeLapse);
  }

  public void OnRspAuthenticate(CThostFtdcRspAuthenticateField pRspAuthenticateField, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspAuthenticate(swigCPtr, this, CThostFtdcRspAuthenticateField.getCPtr(pRspAuthenticateField), pRspAuthenticateField, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspAuthenticateSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcRspAuthenticateField.getCPtr(pRspAuthenticateField), pRspAuthenticateField, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspUserLogin(CThostFtdcRspUserLoginField pRspUserLogin, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspUserLogin(swigCPtr, this, CThostFtdcRspUserLoginField.getCPtr(pRspUserLogin), pRspUserLogin, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspUserLoginSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcRspUserLoginField.getCPtr(pRspUserLogin), pRspUserLogin, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspUserLogout(CThostFtdcUserLogoutField pUserLogout, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspUserLogout(swigCPtr, this, CThostFtdcUserLogoutField.getCPtr(pUserLogout), pUserLogout, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspUserLogoutSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcUserLogoutField.getCPtr(pUserLogout), pUserLogout, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspUserPasswordUpdate(CThostFtdcUserPasswordUpdateField pUserPasswordUpdate, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspUserPasswordUpdate(swigCPtr, this, CThostFtdcUserPasswordUpdateField.getCPtr(pUserPasswordUpdate), pUserPasswordUpdate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspUserPasswordUpdateSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcUserPasswordUpdateField.getCPtr(pUserPasswordUpdate), pUserPasswordUpdate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspTradingAccountPasswordUpdate(CThostFtdcTradingAccountPasswordUpdateField pTradingAccountPasswordUpdate, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspTradingAccountPasswordUpdate(swigCPtr, this, CThostFtdcTradingAccountPasswordUpdateField.getCPtr(pTradingAccountPasswordUpdate), pTradingAccountPasswordUpdate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspTradingAccountPasswordUpdateSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcTradingAccountPasswordUpdateField.getCPtr(pTradingAccountPasswordUpdate), pTradingAccountPasswordUpdate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspOrderInsert(CThostFtdcInputOrderField pInputOrder, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspOrderInsert(swigCPtr, this, CThostFtdcInputOrderField.getCPtr(pInputOrder), pInputOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspOrderInsertSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInputOrderField.getCPtr(pInputOrder), pInputOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspParkedOrderInsert(CThostFtdcParkedOrderField pParkedOrder, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspParkedOrderInsert(swigCPtr, this, CThostFtdcParkedOrderField.getCPtr(pParkedOrder), pParkedOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspParkedOrderInsertSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcParkedOrderField.getCPtr(pParkedOrder), pParkedOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspParkedOrderAction(CThostFtdcParkedOrderActionField pParkedOrderAction, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspParkedOrderAction(swigCPtr, this, CThostFtdcParkedOrderActionField.getCPtr(pParkedOrderAction), pParkedOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspParkedOrderActionSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcParkedOrderActionField.getCPtr(pParkedOrderAction), pParkedOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspOrderAction(CThostFtdcInputOrderActionField pInputOrderAction, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspOrderAction(swigCPtr, this, CThostFtdcInputOrderActionField.getCPtr(pInputOrderAction), pInputOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspOrderActionSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInputOrderActionField.getCPtr(pInputOrderAction), pInputOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQueryMaxOrderVolume(CThostFtdcQueryMaxOrderVolumeField pQueryMaxOrderVolume, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQueryMaxOrderVolume(swigCPtr, this, CThostFtdcQueryMaxOrderVolumeField.getCPtr(pQueryMaxOrderVolume), pQueryMaxOrderVolume, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQueryMaxOrderVolumeSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcQueryMaxOrderVolumeField.getCPtr(pQueryMaxOrderVolume), pQueryMaxOrderVolume, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspSettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField pSettlementInfoConfirm, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspSettlementInfoConfirm(swigCPtr, this, CThostFtdcSettlementInfoConfirmField.getCPtr(pSettlementInfoConfirm), pSettlementInfoConfirm, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspSettlementInfoConfirmSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcSettlementInfoConfirmField.getCPtr(pSettlementInfoConfirm), pSettlementInfoConfirm, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspRemoveParkedOrder(CThostFtdcRemoveParkedOrderField pRemoveParkedOrder, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspRemoveParkedOrder(swigCPtr, this, CThostFtdcRemoveParkedOrderField.getCPtr(pRemoveParkedOrder), pRemoveParkedOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspRemoveParkedOrderSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcRemoveParkedOrderField.getCPtr(pRemoveParkedOrder), pRemoveParkedOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspRemoveParkedOrderAction(CThostFtdcRemoveParkedOrderActionField pRemoveParkedOrderAction, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspRemoveParkedOrderAction(swigCPtr, this, CThostFtdcRemoveParkedOrderActionField.getCPtr(pRemoveParkedOrderAction), pRemoveParkedOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspRemoveParkedOrderActionSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcRemoveParkedOrderActionField.getCPtr(pRemoveParkedOrderAction), pRemoveParkedOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspExecOrderInsert(CThostFtdcInputExecOrderField pInputExecOrder, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspExecOrderInsert(swigCPtr, this, CThostFtdcInputExecOrderField.getCPtr(pInputExecOrder), pInputExecOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspExecOrderInsertSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInputExecOrderField.getCPtr(pInputExecOrder), pInputExecOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspExecOrderAction(CThostFtdcInputExecOrderActionField pInputExecOrderAction, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspExecOrderAction(swigCPtr, this, CThostFtdcInputExecOrderActionField.getCPtr(pInputExecOrderAction), pInputExecOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspExecOrderActionSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInputExecOrderActionField.getCPtr(pInputExecOrderAction), pInputExecOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspForQuoteInsert(CThostFtdcInputForQuoteField pInputForQuote, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspForQuoteInsert(swigCPtr, this, CThostFtdcInputForQuoteField.getCPtr(pInputForQuote), pInputForQuote, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspForQuoteInsertSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInputForQuoteField.getCPtr(pInputForQuote), pInputForQuote, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQuoteInsert(CThostFtdcInputQuoteField pInputQuote, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQuoteInsert(swigCPtr, this, CThostFtdcInputQuoteField.getCPtr(pInputQuote), pInputQuote, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQuoteInsertSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInputQuoteField.getCPtr(pInputQuote), pInputQuote, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQuoteAction(CThostFtdcInputQuoteActionField pInputQuoteAction, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQuoteAction(swigCPtr, this, CThostFtdcInputQuoteActionField.getCPtr(pInputQuoteAction), pInputQuoteAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQuoteActionSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInputQuoteActionField.getCPtr(pInputQuoteAction), pInputQuoteAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspBatchOrderAction(CThostFtdcInputBatchOrderActionField pInputBatchOrderAction, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspBatchOrderAction(swigCPtr, this, CThostFtdcInputBatchOrderActionField.getCPtr(pInputBatchOrderAction), pInputBatchOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspBatchOrderActionSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInputBatchOrderActionField.getCPtr(pInputBatchOrderAction), pInputBatchOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspCombActionInsert(CThostFtdcInputCombActionField pInputCombAction, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspCombActionInsert(swigCPtr, this, CThostFtdcInputCombActionField.getCPtr(pInputCombAction), pInputCombAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspCombActionInsertSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInputCombActionField.getCPtr(pInputCombAction), pInputCombAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryOrder(CThostFtdcOrderField pOrder, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryOrder(swigCPtr, this, CThostFtdcOrderField.getCPtr(pOrder), pOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryOrderSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcOrderField.getCPtr(pOrder), pOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryTrade(CThostFtdcTradeField pTrade, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryTrade(swigCPtr, this, CThostFtdcTradeField.getCPtr(pTrade), pTrade, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryTradeSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcTradeField.getCPtr(pTrade), pTrade, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryInvestorPosition(CThostFtdcInvestorPositionField pInvestorPosition, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInvestorPosition(swigCPtr, this, CThostFtdcInvestorPositionField.getCPtr(pInvestorPosition), pInvestorPosition, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInvestorPositionSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInvestorPositionField.getCPtr(pInvestorPosition), pInvestorPosition, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryTradingAccount(CThostFtdcTradingAccountField pTradingAccount, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryTradingAccount(swigCPtr, this, CThostFtdcTradingAccountField.getCPtr(pTradingAccount), pTradingAccount, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryTradingAccountSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcTradingAccountField.getCPtr(pTradingAccount), pTradingAccount, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryInvestor(CThostFtdcInvestorField pInvestor, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInvestor(swigCPtr, this, CThostFtdcInvestorField.getCPtr(pInvestor), pInvestor, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInvestorSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInvestorField.getCPtr(pInvestor), pInvestor, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryTradingCode(CThostFtdcTradingCodeField pTradingCode, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryTradingCode(swigCPtr, this, CThostFtdcTradingCodeField.getCPtr(pTradingCode), pTradingCode, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryTradingCodeSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcTradingCodeField.getCPtr(pTradingCode), pTradingCode, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryInstrumentMarginRate(CThostFtdcInstrumentMarginRateField pInstrumentMarginRate, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInstrumentMarginRate(swigCPtr, this, CThostFtdcInstrumentMarginRateField.getCPtr(pInstrumentMarginRate), pInstrumentMarginRate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInstrumentMarginRateSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInstrumentMarginRateField.getCPtr(pInstrumentMarginRate), pInstrumentMarginRate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryInstrumentCommissionRate(CThostFtdcInstrumentCommissionRateField pInstrumentCommissionRate, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInstrumentCommissionRate(swigCPtr, this, CThostFtdcInstrumentCommissionRateField.getCPtr(pInstrumentCommissionRate), pInstrumentCommissionRate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInstrumentCommissionRateSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInstrumentCommissionRateField.getCPtr(pInstrumentCommissionRate), pInstrumentCommissionRate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryExchange(CThostFtdcExchangeField pExchange, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryExchange(swigCPtr, this, CThostFtdcExchangeField.getCPtr(pExchange), pExchange, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryExchangeSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcExchangeField.getCPtr(pExchange), pExchange, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryProduct(CThostFtdcProductField pProduct, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryProduct(swigCPtr, this, CThostFtdcProductField.getCPtr(pProduct), pProduct, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryProductSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcProductField.getCPtr(pProduct), pProduct, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryInstrument(CThostFtdcInstrumentField pInstrument, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInstrument(swigCPtr, this, CThostFtdcInstrumentField.getCPtr(pInstrument), pInstrument, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInstrumentSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInstrumentField.getCPtr(pInstrument), pInstrument, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryDepthMarketData(CThostFtdcDepthMarketDataField pDepthMarketData, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryDepthMarketData(swigCPtr, this, CThostFtdcDepthMarketDataField.getCPtr(pDepthMarketData), pDepthMarketData, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryDepthMarketDataSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcDepthMarketDataField.getCPtr(pDepthMarketData), pDepthMarketData, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQrySettlementInfo(CThostFtdcSettlementInfoField pSettlementInfo, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQrySettlementInfo(swigCPtr, this, CThostFtdcSettlementInfoField.getCPtr(pSettlementInfo), pSettlementInfo, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQrySettlementInfoSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcSettlementInfoField.getCPtr(pSettlementInfo), pSettlementInfo, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryTransferBank(CThostFtdcTransferBankField pTransferBank, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryTransferBank(swigCPtr, this, CThostFtdcTransferBankField.getCPtr(pTransferBank), pTransferBank, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryTransferBankSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcTransferBankField.getCPtr(pTransferBank), pTransferBank, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryInvestorPositionDetail(CThostFtdcInvestorPositionDetailField pInvestorPositionDetail, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInvestorPositionDetail(swigCPtr, this, CThostFtdcInvestorPositionDetailField.getCPtr(pInvestorPositionDetail), pInvestorPositionDetail, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInvestorPositionDetailSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInvestorPositionDetailField.getCPtr(pInvestorPositionDetail), pInvestorPositionDetail, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryNotice(CThostFtdcNoticeField pNotice, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryNotice(swigCPtr, this, CThostFtdcNoticeField.getCPtr(pNotice), pNotice, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryNoticeSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcNoticeField.getCPtr(pNotice), pNotice, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQrySettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField pSettlementInfoConfirm, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQrySettlementInfoConfirm(swigCPtr, this, CThostFtdcSettlementInfoConfirmField.getCPtr(pSettlementInfoConfirm), pSettlementInfoConfirm, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQrySettlementInfoConfirmSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcSettlementInfoConfirmField.getCPtr(pSettlementInfoConfirm), pSettlementInfoConfirm, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryInvestorPositionCombineDetail(CThostFtdcInvestorPositionCombineDetailField pInvestorPositionCombineDetail, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInvestorPositionCombineDetail(swigCPtr, this, CThostFtdcInvestorPositionCombineDetailField.getCPtr(pInvestorPositionCombineDetail), pInvestorPositionCombineDetail, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInvestorPositionCombineDetailSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInvestorPositionCombineDetailField.getCPtr(pInvestorPositionCombineDetail), pInvestorPositionCombineDetail, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryCFMMCTradingAccountKey(CThostFtdcCFMMCTradingAccountKeyField pCFMMCTradingAccountKey, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryCFMMCTradingAccountKey(swigCPtr, this, CThostFtdcCFMMCTradingAccountKeyField.getCPtr(pCFMMCTradingAccountKey), pCFMMCTradingAccountKey, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryCFMMCTradingAccountKeySwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcCFMMCTradingAccountKeyField.getCPtr(pCFMMCTradingAccountKey), pCFMMCTradingAccountKey, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryEWarrantOffset(CThostFtdcEWarrantOffsetField pEWarrantOffset, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryEWarrantOffset(swigCPtr, this, CThostFtdcEWarrantOffsetField.getCPtr(pEWarrantOffset), pEWarrantOffset, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryEWarrantOffsetSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcEWarrantOffsetField.getCPtr(pEWarrantOffset), pEWarrantOffset, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryInvestorProductGroupMargin(CThostFtdcInvestorProductGroupMarginField pInvestorProductGroupMargin, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInvestorProductGroupMargin(swigCPtr, this, CThostFtdcInvestorProductGroupMarginField.getCPtr(pInvestorProductGroupMargin), pInvestorProductGroupMargin, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryInvestorProductGroupMarginSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInvestorProductGroupMarginField.getCPtr(pInvestorProductGroupMargin), pInvestorProductGroupMargin, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryExchangeMarginRate(CThostFtdcExchangeMarginRateField pExchangeMarginRate, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryExchangeMarginRate(swigCPtr, this, CThostFtdcExchangeMarginRateField.getCPtr(pExchangeMarginRate), pExchangeMarginRate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryExchangeMarginRateSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcExchangeMarginRateField.getCPtr(pExchangeMarginRate), pExchangeMarginRate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryExchangeMarginRateAdjust(CThostFtdcExchangeMarginRateAdjustField pExchangeMarginRateAdjust, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryExchangeMarginRateAdjust(swigCPtr, this, CThostFtdcExchangeMarginRateAdjustField.getCPtr(pExchangeMarginRateAdjust), pExchangeMarginRateAdjust, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryExchangeMarginRateAdjustSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcExchangeMarginRateAdjustField.getCPtr(pExchangeMarginRateAdjust), pExchangeMarginRateAdjust, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryExchangeRate(CThostFtdcExchangeRateField pExchangeRate, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryExchangeRate(swigCPtr, this, CThostFtdcExchangeRateField.getCPtr(pExchangeRate), pExchangeRate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryExchangeRateSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcExchangeRateField.getCPtr(pExchangeRate), pExchangeRate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQrySecAgentACIDMap(CThostFtdcSecAgentACIDMapField pSecAgentACIDMap, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQrySecAgentACIDMap(swigCPtr, this, CThostFtdcSecAgentACIDMapField.getCPtr(pSecAgentACIDMap), pSecAgentACIDMap, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQrySecAgentACIDMapSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcSecAgentACIDMapField.getCPtr(pSecAgentACIDMap), pSecAgentACIDMap, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryProductExchRate(CThostFtdcProductExchRateField pProductExchRate, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryProductExchRate(swigCPtr, this, CThostFtdcProductExchRateField.getCPtr(pProductExchRate), pProductExchRate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryProductExchRateSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcProductExchRateField.getCPtr(pProductExchRate), pProductExchRate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryProductGroup(CThostFtdcProductGroupField pProductGroup, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryProductGroup(swigCPtr, this, CThostFtdcProductGroupField.getCPtr(pProductGroup), pProductGroup, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryProductGroupSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcProductGroupField.getCPtr(pProductGroup), pProductGroup, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryOptionInstrTradeCost(CThostFtdcOptionInstrTradeCostField pOptionInstrTradeCost, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryOptionInstrTradeCost(swigCPtr, this, CThostFtdcOptionInstrTradeCostField.getCPtr(pOptionInstrTradeCost), pOptionInstrTradeCost, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryOptionInstrTradeCostSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcOptionInstrTradeCostField.getCPtr(pOptionInstrTradeCost), pOptionInstrTradeCost, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryOptionInstrCommRate(CThostFtdcOptionInstrCommRateField pOptionInstrCommRate, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryOptionInstrCommRate(swigCPtr, this, CThostFtdcOptionInstrCommRateField.getCPtr(pOptionInstrCommRate), pOptionInstrCommRate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryOptionInstrCommRateSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcOptionInstrCommRateField.getCPtr(pOptionInstrCommRate), pOptionInstrCommRate, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryExecOrder(CThostFtdcExecOrderField pExecOrder, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryExecOrder(swigCPtr, this, CThostFtdcExecOrderField.getCPtr(pExecOrder), pExecOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryExecOrderSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcExecOrderField.getCPtr(pExecOrder), pExecOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryForQuote(CThostFtdcForQuoteField pForQuote, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryForQuote(swigCPtr, this, CThostFtdcForQuoteField.getCPtr(pForQuote), pForQuote, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryForQuoteSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcForQuoteField.getCPtr(pForQuote), pForQuote, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryQuote(CThostFtdcQuoteField pQuote, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryQuote(swigCPtr, this, CThostFtdcQuoteField.getCPtr(pQuote), pQuote, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryQuoteSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcQuoteField.getCPtr(pQuote), pQuote, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryCombInstrumentGuard(CThostFtdcCombInstrumentGuardField pCombInstrumentGuard, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryCombInstrumentGuard(swigCPtr, this, CThostFtdcCombInstrumentGuardField.getCPtr(pCombInstrumentGuard), pCombInstrumentGuard, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryCombInstrumentGuardSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcCombInstrumentGuardField.getCPtr(pCombInstrumentGuard), pCombInstrumentGuard, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryCombAction(CThostFtdcCombActionField pCombAction, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryCombAction(swigCPtr, this, CThostFtdcCombActionField.getCPtr(pCombAction), pCombAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryCombActionSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcCombActionField.getCPtr(pCombAction), pCombAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryTransferSerial(CThostFtdcTransferSerialField pTransferSerial, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryTransferSerial(swigCPtr, this, CThostFtdcTransferSerialField.getCPtr(pTransferSerial), pTransferSerial, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryTransferSerialSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcTransferSerialField.getCPtr(pTransferSerial), pTransferSerial, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryAccountregister(CThostFtdcAccountregisterField pAccountregister, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryAccountregister(swigCPtr, this, CThostFtdcAccountregisterField.getCPtr(pAccountregister), pAccountregister, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryAccountregisterSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcAccountregisterField.getCPtr(pAccountregister), pAccountregister, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspError(CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspError(swigCPtr, this, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspErrorSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRtnOrder(CThostFtdcOrderField pOrder) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnOrder(swigCPtr, this, CThostFtdcOrderField.getCPtr(pOrder), pOrder); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnOrderSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcOrderField.getCPtr(pOrder), pOrder);
  }

  public void OnRtnTrade(CThostFtdcTradeField pTrade) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnTrade(swigCPtr, this, CThostFtdcTradeField.getCPtr(pTrade), pTrade); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnTradeSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcTradeField.getCPtr(pTrade), pTrade);
  }

  public void OnErrRtnOrderInsert(CThostFtdcInputOrderField pInputOrder, CThostFtdcRspInfoField pRspInfo) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnOrderInsert(swigCPtr, this, CThostFtdcInputOrderField.getCPtr(pInputOrder), pInputOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnOrderInsertSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInputOrderField.getCPtr(pInputOrder), pInputOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
  }

  public void OnErrRtnOrderAction(CThostFtdcOrderActionField pOrderAction, CThostFtdcRspInfoField pRspInfo) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnOrderAction(swigCPtr, this, CThostFtdcOrderActionField.getCPtr(pOrderAction), pOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnOrderActionSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcOrderActionField.getCPtr(pOrderAction), pOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
  }

  public void OnRtnInstrumentStatus(CThostFtdcInstrumentStatusField pInstrumentStatus) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnInstrumentStatus(swigCPtr, this, CThostFtdcInstrumentStatusField.getCPtr(pInstrumentStatus), pInstrumentStatus); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnInstrumentStatusSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInstrumentStatusField.getCPtr(pInstrumentStatus), pInstrumentStatus);
  }

  public void OnRtnTradingNotice(CThostFtdcTradingNoticeInfoField pTradingNoticeInfo) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnTradingNotice(swigCPtr, this, CThostFtdcTradingNoticeInfoField.getCPtr(pTradingNoticeInfo), pTradingNoticeInfo); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnTradingNoticeSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcTradingNoticeInfoField.getCPtr(pTradingNoticeInfo), pTradingNoticeInfo);
  }

  public void OnRtnErrorConditionalOrder(CThostFtdcErrorConditionalOrderField pErrorConditionalOrder) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnErrorConditionalOrder(swigCPtr, this, CThostFtdcErrorConditionalOrderField.getCPtr(pErrorConditionalOrder), pErrorConditionalOrder); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnErrorConditionalOrderSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcErrorConditionalOrderField.getCPtr(pErrorConditionalOrder), pErrorConditionalOrder);
  }

  public void OnRtnExecOrder(CThostFtdcExecOrderField pExecOrder) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnExecOrder(swigCPtr, this, CThostFtdcExecOrderField.getCPtr(pExecOrder), pExecOrder); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnExecOrderSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcExecOrderField.getCPtr(pExecOrder), pExecOrder);
  }

  public void OnErrRtnExecOrderInsert(CThostFtdcInputExecOrderField pInputExecOrder, CThostFtdcRspInfoField pRspInfo) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnExecOrderInsert(swigCPtr, this, CThostFtdcInputExecOrderField.getCPtr(pInputExecOrder), pInputExecOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnExecOrderInsertSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInputExecOrderField.getCPtr(pInputExecOrder), pInputExecOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
  }

  public void OnErrRtnExecOrderAction(CThostFtdcExecOrderActionField pExecOrderAction, CThostFtdcRspInfoField pRspInfo) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnExecOrderAction(swigCPtr, this, CThostFtdcExecOrderActionField.getCPtr(pExecOrderAction), pExecOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnExecOrderActionSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcExecOrderActionField.getCPtr(pExecOrderAction), pExecOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
  }

  public void OnErrRtnForQuoteInsert(CThostFtdcInputForQuoteField pInputForQuote, CThostFtdcRspInfoField pRspInfo) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnForQuoteInsert(swigCPtr, this, CThostFtdcInputForQuoteField.getCPtr(pInputForQuote), pInputForQuote, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnForQuoteInsertSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInputForQuoteField.getCPtr(pInputForQuote), pInputForQuote, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
  }

  public void OnRtnQuote(CThostFtdcQuoteField pQuote) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnQuote(swigCPtr, this, CThostFtdcQuoteField.getCPtr(pQuote), pQuote); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnQuoteSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcQuoteField.getCPtr(pQuote), pQuote);
  }

  public void OnErrRtnQuoteInsert(CThostFtdcInputQuoteField pInputQuote, CThostFtdcRspInfoField pRspInfo) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnQuoteInsert(swigCPtr, this, CThostFtdcInputQuoteField.getCPtr(pInputQuote), pInputQuote, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnQuoteInsertSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInputQuoteField.getCPtr(pInputQuote), pInputQuote, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
  }

  public void OnErrRtnQuoteAction(CThostFtdcQuoteActionField pQuoteAction, CThostFtdcRspInfoField pRspInfo) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnQuoteAction(swigCPtr, this, CThostFtdcQuoteActionField.getCPtr(pQuoteAction), pQuoteAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnQuoteActionSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcQuoteActionField.getCPtr(pQuoteAction), pQuoteAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
  }

  public void OnRtnForQuoteRsp(CThostFtdcForQuoteRspField pForQuoteRsp) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnForQuoteRsp(swigCPtr, this, CThostFtdcForQuoteRspField.getCPtr(pForQuoteRsp), pForQuoteRsp); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnForQuoteRspSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcForQuoteRspField.getCPtr(pForQuoteRsp), pForQuoteRsp);
  }

  public void OnRtnCFMMCTradingAccountToken(CThostFtdcCFMMCTradingAccountTokenField pCFMMCTradingAccountToken) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnCFMMCTradingAccountToken(swigCPtr, this, CThostFtdcCFMMCTradingAccountTokenField.getCPtr(pCFMMCTradingAccountToken), pCFMMCTradingAccountToken); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnCFMMCTradingAccountTokenSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcCFMMCTradingAccountTokenField.getCPtr(pCFMMCTradingAccountToken), pCFMMCTradingAccountToken);
  }

  public void OnErrRtnBatchOrderAction(CThostFtdcBatchOrderActionField pBatchOrderAction, CThostFtdcRspInfoField pRspInfo) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnBatchOrderAction(swigCPtr, this, CThostFtdcBatchOrderActionField.getCPtr(pBatchOrderAction), pBatchOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnBatchOrderActionSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcBatchOrderActionField.getCPtr(pBatchOrderAction), pBatchOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
  }

  public void OnRtnCombAction(CThostFtdcCombActionField pCombAction) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnCombAction(swigCPtr, this, CThostFtdcCombActionField.getCPtr(pCombAction), pCombAction); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnCombActionSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcCombActionField.getCPtr(pCombAction), pCombAction);
  }

  public void OnErrRtnCombActionInsert(CThostFtdcInputCombActionField pInputCombAction, CThostFtdcRspInfoField pRspInfo) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnCombActionInsert(swigCPtr, this, CThostFtdcInputCombActionField.getCPtr(pInputCombAction), pInputCombAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnCombActionInsertSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcInputCombActionField.getCPtr(pInputCombAction), pInputCombAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
  }

  public void OnRspQryContractBank(CThostFtdcContractBankField pContractBank, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryContractBank(swigCPtr, this, CThostFtdcContractBankField.getCPtr(pContractBank), pContractBank, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryContractBankSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcContractBankField.getCPtr(pContractBank), pContractBank, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryParkedOrder(CThostFtdcParkedOrderField pParkedOrder, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryParkedOrder(swigCPtr, this, CThostFtdcParkedOrderField.getCPtr(pParkedOrder), pParkedOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryParkedOrderSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcParkedOrderField.getCPtr(pParkedOrder), pParkedOrder, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryParkedOrderAction(CThostFtdcParkedOrderActionField pParkedOrderAction, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryParkedOrderAction(swigCPtr, this, CThostFtdcParkedOrderActionField.getCPtr(pParkedOrderAction), pParkedOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryParkedOrderActionSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcParkedOrderActionField.getCPtr(pParkedOrderAction), pParkedOrderAction, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryTradingNotice(CThostFtdcTradingNoticeField pTradingNotice, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryTradingNotice(swigCPtr, this, CThostFtdcTradingNoticeField.getCPtr(pTradingNotice), pTradingNotice, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryTradingNoticeSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcTradingNoticeField.getCPtr(pTradingNotice), pTradingNotice, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryBrokerTradingParams(CThostFtdcBrokerTradingParamsField pBrokerTradingParams, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryBrokerTradingParams(swigCPtr, this, CThostFtdcBrokerTradingParamsField.getCPtr(pBrokerTradingParams), pBrokerTradingParams, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryBrokerTradingParamsSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcBrokerTradingParamsField.getCPtr(pBrokerTradingParams), pBrokerTradingParams, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQryBrokerTradingAlgos(CThostFtdcBrokerTradingAlgosField pBrokerTradingAlgos, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryBrokerTradingAlgos(swigCPtr, this, CThostFtdcBrokerTradingAlgosField.getCPtr(pBrokerTradingAlgos), pBrokerTradingAlgos, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQryBrokerTradingAlgosSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcBrokerTradingAlgosField.getCPtr(pBrokerTradingAlgos), pBrokerTradingAlgos, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQueryCFMMCTradingAccountToken(CThostFtdcQueryCFMMCTradingAccountTokenField pQueryCFMMCTradingAccountToken, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQueryCFMMCTradingAccountToken(swigCPtr, this, CThostFtdcQueryCFMMCTradingAccountTokenField.getCPtr(pQueryCFMMCTradingAccountToken), pQueryCFMMCTradingAccountToken, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQueryCFMMCTradingAccountTokenSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcQueryCFMMCTradingAccountTokenField.getCPtr(pQueryCFMMCTradingAccountToken), pQueryCFMMCTradingAccountToken, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRtnFromBankToFutureByBank(CThostFtdcRspTransferField pRspTransfer) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnFromBankToFutureByBank(swigCPtr, this, CThostFtdcRspTransferField.getCPtr(pRspTransfer), pRspTransfer); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnFromBankToFutureByBankSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcRspTransferField.getCPtr(pRspTransfer), pRspTransfer);
  }

  public void OnRtnFromFutureToBankByBank(CThostFtdcRspTransferField pRspTransfer) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnFromFutureToBankByBank(swigCPtr, this, CThostFtdcRspTransferField.getCPtr(pRspTransfer), pRspTransfer); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnFromFutureToBankByBankSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcRspTransferField.getCPtr(pRspTransfer), pRspTransfer);
  }

  public void OnRtnRepealFromBankToFutureByBank(CThostFtdcRspRepealField pRspRepeal) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnRepealFromBankToFutureByBank(swigCPtr, this, CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnRepealFromBankToFutureByBankSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
  }

  public void OnRtnRepealFromFutureToBankByBank(CThostFtdcRspRepealField pRspRepeal) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnRepealFromFutureToBankByBank(swigCPtr, this, CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnRepealFromFutureToBankByBankSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
  }

  public void OnRtnFromBankToFutureByFuture(CThostFtdcRspTransferField pRspTransfer) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnFromBankToFutureByFuture(swigCPtr, this, CThostFtdcRspTransferField.getCPtr(pRspTransfer), pRspTransfer); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnFromBankToFutureByFutureSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcRspTransferField.getCPtr(pRspTransfer), pRspTransfer);
  }

  public void OnRtnFromFutureToBankByFuture(CThostFtdcRspTransferField pRspTransfer) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnFromFutureToBankByFuture(swigCPtr, this, CThostFtdcRspTransferField.getCPtr(pRspTransfer), pRspTransfer); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnFromFutureToBankByFutureSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcRspTransferField.getCPtr(pRspTransfer), pRspTransfer);
  }

  public void OnRtnRepealFromBankToFutureByFutureManual(CThostFtdcRspRepealField pRspRepeal) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnRepealFromBankToFutureByFutureManual(swigCPtr, this, CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnRepealFromBankToFutureByFutureManualSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
  }

  public void OnRtnRepealFromFutureToBankByFutureManual(CThostFtdcRspRepealField pRspRepeal) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnRepealFromFutureToBankByFutureManual(swigCPtr, this, CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnRepealFromFutureToBankByFutureManualSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
  }

  public void OnRtnQueryBankBalanceByFuture(CThostFtdcNotifyQueryAccountField pNotifyQueryAccount) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnQueryBankBalanceByFuture(swigCPtr, this, CThostFtdcNotifyQueryAccountField.getCPtr(pNotifyQueryAccount), pNotifyQueryAccount); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnQueryBankBalanceByFutureSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcNotifyQueryAccountField.getCPtr(pNotifyQueryAccount), pNotifyQueryAccount);
  }

  public void OnErrRtnBankToFutureByFuture(CThostFtdcReqTransferField pReqTransfer, CThostFtdcRspInfoField pRspInfo) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnBankToFutureByFuture(swigCPtr, this, CThostFtdcReqTransferField.getCPtr(pReqTransfer), pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnBankToFutureByFutureSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcReqTransferField.getCPtr(pReqTransfer), pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
  }

  public void OnErrRtnFutureToBankByFuture(CThostFtdcReqTransferField pReqTransfer, CThostFtdcRspInfoField pRspInfo) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnFutureToBankByFuture(swigCPtr, this, CThostFtdcReqTransferField.getCPtr(pReqTransfer), pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnFutureToBankByFutureSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcReqTransferField.getCPtr(pReqTransfer), pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
  }

  public void OnErrRtnRepealBankToFutureByFutureManual(CThostFtdcReqRepealField pReqRepeal, CThostFtdcRspInfoField pRspInfo) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnRepealBankToFutureByFutureManual(swigCPtr, this, CThostFtdcReqRepealField.getCPtr(pReqRepeal), pReqRepeal, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnRepealBankToFutureByFutureManualSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcReqRepealField.getCPtr(pReqRepeal), pReqRepeal, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
  }

  public void OnErrRtnRepealFutureToBankByFutureManual(CThostFtdcReqRepealField pReqRepeal, CThostFtdcRspInfoField pRspInfo) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnRepealFutureToBankByFutureManual(swigCPtr, this, CThostFtdcReqRepealField.getCPtr(pReqRepeal), pReqRepeal, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnRepealFutureToBankByFutureManualSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcReqRepealField.getCPtr(pReqRepeal), pReqRepeal, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
  }

  public void OnErrRtnQueryBankBalanceByFuture(CThostFtdcReqQueryAccountField pReqQueryAccount, CThostFtdcRspInfoField pRspInfo) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnQueryBankBalanceByFuture(swigCPtr, this, CThostFtdcReqQueryAccountField.getCPtr(pReqQueryAccount), pReqQueryAccount, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnErrRtnQueryBankBalanceByFutureSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcReqQueryAccountField.getCPtr(pReqQueryAccount), pReqQueryAccount, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo);
  }

  public void OnRtnRepealFromBankToFutureByFuture(CThostFtdcRspRepealField pRspRepeal) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnRepealFromBankToFutureByFuture(swigCPtr, this, CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnRepealFromBankToFutureByFutureSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
  }

  public void OnRtnRepealFromFutureToBankByFuture(CThostFtdcRspRepealField pRspRepeal) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnRepealFromFutureToBankByFuture(swigCPtr, this, CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnRepealFromFutureToBankByFutureSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcRspRepealField.getCPtr(pRspRepeal), pRspRepeal);
  }

  public void OnRspFromBankToFutureByFuture(CThostFtdcReqTransferField pReqTransfer, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspFromBankToFutureByFuture(swigCPtr, this, CThostFtdcReqTransferField.getCPtr(pReqTransfer), pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspFromBankToFutureByFutureSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcReqTransferField.getCPtr(pReqTransfer), pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspFromFutureToBankByFuture(CThostFtdcReqTransferField pReqTransfer, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspFromFutureToBankByFuture(swigCPtr, this, CThostFtdcReqTransferField.getCPtr(pReqTransfer), pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspFromFutureToBankByFutureSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcReqTransferField.getCPtr(pReqTransfer), pReqTransfer, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRspQueryBankAccountMoneyByFuture(CThostFtdcReqQueryAccountField pReqQueryAccount, CThostFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQueryBankAccountMoneyByFuture(swigCPtr, this, CThostFtdcReqQueryAccountField.getCPtr(pReqQueryAccount), pReqQueryAccount, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRspQueryBankAccountMoneyByFutureSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcReqQueryAccountField.getCPtr(pReqQueryAccount), pReqQueryAccount, CThostFtdcRspInfoField.getCPtr(pRspInfo), pRspInfo, nRequestID, bIsLast);
  }

  public void OnRtnOpenAccountByBank(CThostFtdcOpenAccountField pOpenAccount) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnOpenAccountByBank(swigCPtr, this, CThostFtdcOpenAccountField.getCPtr(pOpenAccount), pOpenAccount); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnOpenAccountByBankSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcOpenAccountField.getCPtr(pOpenAccount), pOpenAccount);
  }

  public void OnRtnCancelAccountByBank(CThostFtdcCancelAccountField pCancelAccount) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnCancelAccountByBank(swigCPtr, this, CThostFtdcCancelAccountField.getCPtr(pCancelAccount), pCancelAccount); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnCancelAccountByBankSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcCancelAccountField.getCPtr(pCancelAccount), pCancelAccount);
  }

  public void OnRtnChangeAccountByBank(CThostFtdcChangeAccountField pChangeAccount) {
    if (getClass() == CThostFtdcTraderSpi.class) CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnChangeAccountByBank(swigCPtr, this, CThostFtdcChangeAccountField.getCPtr(pChangeAccount), pChangeAccount); else CTP_wrap4javaJNI.CThostFtdcTraderSpi_OnRtnChangeAccountByBankSwigExplicitCThostFtdcTraderSpi(swigCPtr, this, CThostFtdcChangeAccountField.getCPtr(pChangeAccount), pChangeAccount);
  }

  public CThostFtdcTraderSpi() {
    this(CTP_wrap4javaJNI.new_CThostFtdcTraderSpi(), true);
    CTP_wrap4javaJNI.CThostFtdcTraderSpi_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
