/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.phenix.orderrouter.ctp;

public class CThostFtdcSyncStatusField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcSyncStatusField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcSyncStatusField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CTP_wrap4javaJNI.delete_CThostFtdcSyncStatusField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradingDay(String value) {
    CTP_wrap4javaJNI.CThostFtdcSyncStatusField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return CTP_wrap4javaJNI.CThostFtdcSyncStatusField_TradingDay_get(swigCPtr, this);
  }

  public void setDataSyncStatus(char value) {
    CTP_wrap4javaJNI.CThostFtdcSyncStatusField_DataSyncStatus_set(swigCPtr, this, value);
  }

  public char getDataSyncStatus() {
    return CTP_wrap4javaJNI.CThostFtdcSyncStatusField_DataSyncStatus_get(swigCPtr, this);
  }

  public CThostFtdcSyncStatusField() {
    this(CTP_wrap4javaJNI.new_CThostFtdcSyncStatusField(), true);
  }

  public void CopyTo(CThostFtdcSyncStatusField r) {
    CTP_wrap4javaJNI.CThostFtdcSyncStatusField_CopyTo(swigCPtr, this, CThostFtdcSyncStatusField.getCPtr(r), r);
  }

}
